[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "soccer-backend"

[services.source]
repo = "your-username/soccer-app"
branch = "main"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app/backend"
ENVIRONMENT = "production"

[services.domains]
generate = true

[services.build]
buildCommand = "cd backend && pip install -r requirements.txt"

[services.healthcheck]
path = "/health"
timeout = 30
interval = 30

[services.resources]
memory = 2048
cpu = 1000

[services.volumes]
- name = "uploads"
  mountPath = "/app/uploads"
  size = 5